version: "3"

tasks:
  init:
    cmds:
      - task: down
      - task: pull
      - task: build

  restart:
    cmds:
      - task: down
      - task: up

  up:
    cmds:
      - docker-compose up -d nginx phpmyadmin

  stop:
    cmds:
      - docker-compose stop

  down:
    cmds:
      - docker-compose down -v --remove-orphans

  pull:
    cmds:
      - docker-compose pull

  build:
    cmds:
      - docker-compose build
